/**
 * Eclipse Cabinetry — Door, Drawer Front & Drawer Box Data
 * Door group charges (C3): A=$0, B=$44, C=$88, D=$150 PER DOOR
 */

export const DOOR_GROUP_CHARGES = { A: 0, B: 44, C: 88, D: 150 };

export const DOORS = [
  { v: "METRO", l: "Metropolitan (Slab)", g: "A" },
  { v: "MET-V", l: "Metropolitan Vertical Grain", g: "A" },
  { v: "MET-H", l: "Metropolitan Horizontal Grain", g: "A" },
  { v: "MET-MDF", l: "Metropolitan MDF (Painted M1)", g: "A" },
  { v: "AFP", l: "Arch Flat Panel", g: "A" }, { v: "ARP", l: "Arch Raised Panel", g: "A" },
  { v: "BCP", l: "Beaded Century", g: "B" }, { v: "CHRS", l: "Charleston Appl. Mould.", g: "B" },
  { v: "CFP", l: "Crown Flat Panel", g: "A" }, { v: "CRP", l: "Crown Raised Panel", g: "A" },
  { v: "GRNS", l: "Greensboro Flat Panel", g: "A" }, { v: "HNVR", l: "Hanover Flat Panel", g: "A" },
  { v: "MNTG", l: "Montgomery Appl. Mould.", g: "B" }, { v: "NHVN", l: "New Haven Flat Panel", g: "A" },
  { v: "OXRP", l: "Oxford Raised Panel", g: "A" }, { v: "RCMD", l: "Richmond Raised Panel", g: "A" },
  { v: "SFP", l: "Square Flat Panel", g: "A" }, { v: "SMST", l: "Somerset Flat Panel", g: "A" },
  { v: "SRP", l: "Square Raised Panel", g: "A" }, { v: "WARD", l: "Ward Flat Panel", g: "A" },
  { v: "SCDL", l: "Scottsdale Flat Panel", g: "A" }, { v: "WMTN", l: "Wilmington Flat Panel", g: "A" },
  { v: "ASPN", l: "Aspen Flat Panel", g: "A" }, { v: "BRST", l: "Bristol Flat Panel", g: "A" },
  { v: "HRTG", l: "Heritage Flat Panel", g: "A" }, { v: "HTFD", l: "Hartford Flat Panel", g: "A" },
  { v: "LNCR", l: "Lancaster Flat Panel", g: "A" }, { v: "HMLN", l: "Hamlin Raised Panel", g: "A" },
  { v: "TAHOE", l: "Tahoe Flat Panel", g: "A" }, { v: "SUMT", l: "Summit Raised Panel", g: "A" },
  { v: "STSVL", l: "Statesville Flat Panel", g: "A" },
  { v: "MLBU", l: "Malibu Flat Panel", g: "A" }, { v: "NAPA-H", l: "Napa Horizontal", g: "A" },
  { v: "NAPA-V", l: "Napa Vertical", g: "A" }, { v: "CNCD", l: "Concord Flat Panel", g: "A" },
  { v: "RMLB", l: "Reeded Malibu", g: "B" },
  { v: "ASVL", l: "Asherville Miter RP", g: "B" }, { v: "BDFD", l: "Bradford Miter RP", g: "B" },
  { v: "DLTN", l: "Dalton Miter FP", g: "B" }, { v: "ESSX", l: "Essex Miter FP", g: "B" },
  { v: "GLBK", l: "Glenbrook Miter FP", g: "B" }, { v: "KNDL", l: "Kendall Miter FP", g: "B" },
  { v: "LNDS", l: "Landes Miter FP", g: "B" }, { v: "PTLN", l: "Portland Miter RP", g: "B" },
  { v: "MNCH", l: "Manchester Miter RP", g: "B" }, { v: "SVNH", l: "Savannah Miter RP", g: "B" },
  { v: "WNSR", l: "Windsor Miter FP", g: "B" }, { v: "SHBY", l: "Shelby Miter FP", g: "B" },
  { v: "GFD", l: "Glass Frame Door", g: "A", x: 0 },
  { v: "CMD", l: "Country Mullion (9 lite)", g: "A", x: 210 },
  { v: "FMD", l: "Fairfield Mullion (11 lite)", g: "A", x: 210 },
  { v: "MD", l: "Mullion Door", g: "A", x: 210 },
  { v: "OEMD", l: "Old English Mullion", g: "A", x: 210 },
  { v: "TMD", l: "Triple Mullion", g: "A", x: 210 },
  { v: "XMD", l: "X Mullion (4 lite)", g: "A", x: 825 },
  { v: "DXMD", l: "Double X Mullion (7 lite)", g: "A", x: 1171 },
  { v: "DXHMD", l: "Double X Horiz. Mullion", g: "A", x: 1179 },
  { v: "TXMD", l: "Triple X Mullion (10 lite)", g: "A", x: 1517 },
  { v: "TXHMD", l: "Triple X Horiz. Mullion", g: "A", x: 1540 },
  { v: "DBMD", l: "Double Bow Mullion", g: "A", x: 1254 },
  { v: "SEMD", l: "Single Elliptical Mullion", g: "A", x: 1558 },
  { v: "DEMD", l: "Double Elliptical Mullion", g: "A", x: 1844 },
  { v: "DLMD", l: "Diamond Left Mullion", g: "A", x: 1844 },
  { v: "DRMD", l: "Diamond Right Mullion", g: "A", x: 1844 },
  { v: "Pane7-P", l: 'Pane 7" Solid Panel', g: "A", x: 29 },
  { v: "Pane7-1", l: 'Pane 7" GFD', g: "A", x: 29 },
  { v: "Pane12-P", l: 'Pane 12" Solid Panel', g: "A", x: 29 },
  { v: "Pane12-1", l: 'Pane 12" GFD', g: "A", x: 29 },
  { v: "Pane7-2", l: 'Pane 7" 2-Lite Mullion', g: "A", x: 76 },
  { v: "Pane7-4", l: 'Pane 7" 4-Lite Mullion', g: "A", x: 76 },
  { v: "Pane12-2", l: 'Pane 12" 2-Lite Mullion', g: "A", x: 107 },
  { v: "Pane12-4", l: 'Pane 12" 4-Lite Mullion', g: "A", x: 107 },
  { v: "LAGFD", l: "Left Arch Glass Frame", g: "A", x: 121 },
  { v: "RAGFD", l: "Right Arch Glass Frame", g: "A", x: 121 },
  { v: "LARP", l: "Left Arch Raised Panel", g: "A", x: 242 },
  { v: "RARP", l: "Right Arch Raised Panel", g: "A", x: 242 },
  { v: "LCTD", l: "Left Contour Door", g: "A", x: 90 },
  { v: "RCTD", l: "Right Contour Door", g: "A", x: 90 },
  { v: "BD1", l: "Bridged - Drawer+Door", g: "A" },
  { v: "BD2", l: "Bridged - 2 Drawer Stack", g: "A" },
  { v: "BD3", l: "Bridged - 3 Drawer Stack", g: "A" },
  { v: "BD4", l: "Bridged - 4 Drawer Stack", g: "A" },
];

export const DRAWER_FRONTS = [
  { v: "DF-MET", l: "Metropolitan (Slab)", g: "A" },
  { v: "DF-MET-V", l: "Metropolitan Vertical Grain", g: "A" },
  { v: "DF-MET-H", l: "Metropolitan Horizontal Grain", g: "A" },
  { v: "DF-MET-MDF", l: "Metropolitan MDF (Painted M1)", g: "A" }, { v: "DF-S", l: "Slab", g: "A" }, { v: "DF-SCLPT", l: "Sculpted", g: "A" },
  { v: "DF-BCP", l: "Beaded Century", g: "B" }, { v: "DF2.5-BCP", l: "Beaded Century (2.5 rail)", g: "B" },
  { v: "DF-CHRS", l: "Charleston", g: "B" },
  { v: "DF-FP", l: "Flat Panel", g: "B" }, { v: "DF2.5-SFP", l: "Square Flat Panel (2.5 rail)", g: "B" },
  { v: "DF-GRNS", l: "Greensboro", g: "B" }, { v: "DF2.5-GRNS", l: "Greensboro (2.5 rail)", g: "B" },
  { v: "DF-HNVR", l: "Hanover", g: "B" }, { v: "DF2.5-HNVR", l: "Hanover (2.5 rail)", g: "B" },
  { v: "DF-MNTG", l: "Montgomery", g: "B" },
  { v: "DF-NHVN", l: "New Haven", g: "B" }, { v: "DF2.5-NHVN", l: "New Haven (2.5 rail)", g: "B" },
  { v: "DF-OXRP", l: "Oxford Raised Panel", g: "B" }, { v: "DF-RCMD", l: "Richmond", g: "B" },
  { v: "DF-RP", l: "Raised Panel", g: "B" }, { v: "DF-SRP", l: "Shaker Raised Panel", g: "B" },
  { v: "DF-SCDL", l: "Scottsdale", g: "B" }, { v: "DF2.5-SCDL", l: "Scottsdale (2.5 rail)", g: "B" },
  { v: "DF-SFP", l: "Square Flat Panel", g: "B" },
  { v: "DF-SMST", l: "Somerset", g: "B" }, { v: "DF2.5-SMST", l: "Somerset (2.5 rail)", g: "B" },
  { v: "DF-WARD", l: "Ward", g: "B" }, { v: "DF2.5-WARD", l: "Ward (2.5 rail)", g: "B" },
  { v: "DF-WMTN", l: "Wilmington", g: "B" }, { v: "DF2.5-WMTN", l: "Wilmington (2.5 rail)", g: "B" },
  { v: "DF-AFP", l: "Arch Flat Panel", g: "B" }, { v: "DF-ARP", l: "Arch Raised Panel", g: "B" },
  { v: "DF-CFP", l: "Crown Flat Panel", g: "B" }, { v: "DF-CRP", l: "Crown Raised Panel", g: "B" },
  { v: "DF-ASPN", l: "Aspen", g: "B" }, { v: "DF-BRST", l: "Bristol", g: "B" }, { v: "DF-HMLN", l: "Hamlin", g: "B" },
  { v: "DF-HRTG", l: "Heritage", g: "B" }, { v: "DF-HTFD", l: "Hartford", g: "B" }, { v: "DF-LNCR", l: "Lancaster", g: "B" },
  { v: "DF-TAHOE", l: "Tahoe", g: "B" }, { v: "DF-SUMT", l: "Summit", g: "B" }, { v: "DF-STSVL", l: "Statesville", g: "B" },
  { v: "DF-CNCD", l: "Concord", g: "B" }, { v: "DF-RMLB", l: "Reeded Malibu", g: "B" },
  { v: "DF-NAPA-V", l: "Napa 5-Piece (Vertical)", g: "B" }, { v: "DF-NAPA-H", l: "Napa 5-Piece (Horizontal)", g: "B" },
  { v: "DF-MLBU", l: "Malibu 5-Piece", g: "B" },
  { v: "DF-ASVL", l: "Asherville Miter", g: "B" }, { v: "DF-BDFD", l: "Bradford Miter", g: "B" },
  { v: "DF-DLTN", l: "Dalton Miter", g: "B" }, { v: "DF-ESSX", l: "Essex Miter", g: "B" },
  { v: "DF-GLBK", l: "Glenbrook Miter", g: "B" }, { v: "DF-KNDL", l: "Kendall Miter", g: "B" },
  { v: "DF-LNDS", l: "Landes Miter", g: "B" }, { v: "DF-PTLN", l: "Portland Miter", g: "B" },
  { v: "DF-MNCH", l: "Manchester Miter", g: "B" }, { v: "DF-SVNH", l: "Savannah Miter", g: "B" },
  { v: "DF-WNSR", l: "Windsor Miter", g: "B" }, { v: "DF-SHBY", l: "Shelby Miter", g: "B" },
  { v: "DFS-OXRP", l: "Shaped Oxford", g: "A" }, { v: "DFS-RCMD", l: "Shaped Richmond", g: "A" },
  { v: "DFS-SRP", l: "Shaped Shaker", g: "A" },
];

export const DRAWER_BOXES = [
  { v: "5/8-STD", l: '5/8" Std Hdwd Dovetail / Blum Tandem Edge', price: 0 },
  { v: "5/8-SM", l: '5/8" Simulated Metal / Blum Tandem Edge', price: 0 },
  { v: "3/4-PREM", l: '3/4" Premium Dovetail (+$57/drw)', price: 57 },
  { v: "LEGRA", l: 'Legrabox SS (+$372/drw)', price: 372 },
  { v: "5/8-STD-FE", l: '5/8" Std Hdwd / Blum Full Ext (+$72/drw)', price: 72 },
  { v: "5/8-SM-FE", l: '5/8" Sim Metal / Blum Full Ext (+$72/drw)', price: 72 },
  { v: "3/4-PREM-FE", l: '3/4" Premium Dovetail / Blum Full Ext (+$129/drw)', price: 129 },
];

export function findDoor(code) { return DOORS.find(d => d.v === code); }
export function findDrawerFront(code) { return DRAWER_FRONTS.find(d => d.v === code); }
export function findDrawerBox(code) { return DRAWER_BOXES.find(d => d.v === code); }
